# Generated by Django 3.2 on 2021-05-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_commentreplies_commentreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreply',
            old_name='commented_on',
            new_name='replied_on',
        ),
    ]
