# Generated by Django 3.2 on 2021-05-08 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_alter_blogpost_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['is_published']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='liked',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_post_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
